// Generated by CoffeeScript 1.6.2
(function() {
  var applescript, as, cronJob, crontime, exec, job;

  applescript = require("applescript");

  exec = require("child_process").exec;

  cronJob = require('cron').CronJob;

  crontime = "*/1 * * * *";

  as = "if application \"Twitter\" is running\n  true\nelse\n  false\nend if";

  job = new cronJob({
    cronTime: crontime,
    onTick: function() {
      var _this = this;

      return applescript.execString(as, function(err, rtn) {
        var base, command, sh, space, tuple;

        if (err) {
          throw err;
        }
        if (rtn === "true") {
          command = "linda-rocketio write";
          tuple = "-tuple '[\"twitter\", \"@takumibaba がついったーを開いています。罵ってあげてください。\"]'";
          base = "-base http://linda.masuilab.org";
          space = "-space takumibaba";
          sh = "" + command + " " + tuple + " " + base + " " + space;
          return exec(sh, function(err, stdout, stderr) {
            if (err) {
              throw err;
            }
            if (stderr) {
              throw stderr;
            }
            return console.log(stdout);
          });
        } else {
          return console.log('false');
        }
      });
    },
    onComplete: function() {
      return console.log('complete');
    },
    start: false,
    timeZone: "Japan/Tokyo"
  });

  job.start();

}).call(this);
